#!/usr/bin/env python

import os
from fabricate import *

###################################################################################################
#                                 Custom configurations                                           #
###################################################################################################

# Executable name
EXEC_NAME = 'linearregression'

# Source for current project
sources = ['LinearRegressionCpuCode']

# DFE_PRJ
DFE_PRJs = ['LinearRegression']

# Platform
platform = os.environ['MAXCOMPILER_TARGET'] if 'MAXCOMPILER_TARGET' in os.environ else 'SIMULATION'

# Include other C projects
C_PRJs = []

# Flags
cflags = '-std=gnu99 -finstrument-functions -fopenmp -fPIC -W -Wall'
ldflags = '-fopenmp'

# Macros for compiling
MACROS = ''



###################################################################################################
#                                         Targets                                                 #
###################################################################################################

prj_root = os.path.dirname(os.path.dirname(os.path.dirname(os.getcwd()))) + '/'
setup(dirs=['.', prj_root])


def build():
	compile('build', cflags)
	link('build', ldflags)


def compile(build_dir, flags):

	# Include SLiC headers
	flags = flags + ' ' + shell("slic-config", "--cflags").strip().replace('\'', '')

	# Compile .max files into .o files
	for dfe in DFE_PRJs:
		max_dir = os.path.join(prj_root, "PLATFORMS", platform, "Maxfiles", dfe)
		sapi_dir = os.path.join(prj_root,"PLATFORMS",platform,"SAPI", dfe)
		if not os.path.isdir(sapi_dir):
			run('mkdir', '-p', sapi_dir)
		for maxfile in os.listdir(max_dir):
			if maxfile.endswith(".max"):
				max_abs = os.path.join(max_dir, os.path.basename(maxfile))
				slic_abs = os.path.join(sapi_dir,os.path.splitext(maxfile)[0] + ".o")
				if os.path.isfile(max_abs):
					run ('sliccompile',  max_abs, slic_abs)


	# Include all SAPI directories
	inc_sapi = ['-I' + os.path.join(prj_root, "PLATFORMS", platform, "SAPI", dfe) for dfe in DFE_PRJs]

	# Include C projects directories
	inc_c = ['-I' + os.path.join(prj_root, "PLATFORMS", platform, "MAPI", c_prj) for c_prj in C_PRJs]

	# Create buld directory
	if not os.path.isdir(build_dir):
		run ('mkdir', '-p', build_dir)

	# Compile source code
	for source in sources:
		run ('gcc', '-c', os.path.join('src', source+'.c'), '-o', os.path.join(build_dir, source+'.o'), flags.split(), inc_sapi, inc_c, MACROS.split())


def link (build_dir, flags):

	# Include SLiC libraries
	flags = flags + ' ' + shell("slic-config", "--libs").strip().replace('\'', '')

	# Object files
	objects = [os.path.join(build_dir, s+'.o') for s in sources]

	slic_objects = []
	for dfe in DFE_PRJs:
		sapi_dir = os.path.join(prj_root, "PLATFORMS", platform,"SAPI", dfe)
		for obj in os.listdir(sapi_dir):
			if obj.endswith(".o"):
				slic_abs = os.path.join(sapi_dir, os.path.basename(obj))
				slic_objects.append(slic_abs)

	mapi_libs = []
	for c_prj in C_PRJs:
		c_dir = os.path.join(prj_root, "PLATFORMS", platform, "MAPI", c_prj)
		for obj in os.listdir(c_dir):
			if obj.endswith(".a"):
				c_abs = os.path.join(c_dir, os.path.basename(obj))
				mapi_libs.append(c_abs)

	# Link object file and make an executable
	run ('gcc', objects, slic_objects, mapi_libs, '-o', os.path.join(build_dir,EXEC_NAME), flags.split())

	# Making new directory for this project and copying executable
	bin_dir = os.path.join(prj_root, "PLATFORMS", platform, 'Maxfiles', os.path.basename(os.getcwd()))
	if not os.path.isdir(build_dir):
		r.gitun ('mkdir', '-p', bin_dir)
	run ('cp', os.path.join(build_dir,EXEC_NAME), bin_dir)

def clean():
	autoclean()

main ()
